# Cadence Configuration for UNet++ Training
# Supported backbones: resnet18, resnet50, resnet101, mobilevit, mobilenetv4_hybrid

executions:
  # Execution 1: ResNet50 with Deep Supervision (Recommended)
  - name: "Train UNet++ ResNet50"
    script: training_unetpp.py
    args:
      - --backbone
      - resnet50
      - --deep_supervision
      - --visualize
    environment:
      python_version: "3.10"
      requirements: requirements.txt
    resources:
      gpu: A10
      gpu_count: 1
      memory: 32GB
    timeout: 6h
    description: "Train UNet++ with ResNet50 backbone (recommended)"

  # Execution 2: ResNet18 (Fastest)
  - name: "Train UNet++ ResNet18"
    script: training_unetpp.py
    args:
      - --backbone
      - resnet18
      - --deep_supervision
      - --visualize
    environment:
      python_version: "3.10"
      requirements: requirements.txt
    resources:
      gpu: T4
      gpu_count: 1
      memory: 24GB
    timeout: 3h
    description: "Train UNet++ with ResNet18 backbone (fastest)"

  # Execution 3: ResNet101 with Deep Supervision (Best Accuracy)
  - name: "Train UNet++ ResNet101"
    script: training_unetpp.py
    args:
      - --backbone
      - resnet101
      - --deep_supervision
      - --visualize
    environment:
      python_version: "3.10"
      requirements: requirements.txt
    resources:
      gpu: A10  # Larger model needs more memory
      gpu_count: 1
      memory: 32GB
    timeout: 8h
    description: "Train UNet++ with ResNet101 backbone (best accuracy)"

  # Execution 4: MobileViT (Fast & Light)
  - name: "Train UNet++ MobileViT"
    script: training_unetpp.py
    args:
      - --backbone
      - mobilevit
      - --deep_supervision
      - --visualize
    environment:
      python_version: "3.10"
      requirements: requirements.txt
    resources:
      gpu: T4
      gpu_count: 1
      memory: 24GB
    timeout: 4h
    description: "Train UNet++ with MobileViT backbone (mobile-friendly)"

  # Execution 5: MobileNetV4 Hybrid
  - name: "Train UNet++ MobileNetV4"
    script: training_unetpp.py
    args:
      - --backbone
      - mobilenetv4_hybrid
      - --deep_supervision
      - --visualize
    environment:
      python_version: "3.10"
      requirements: requirements.txt
    resources:
      gpu: T4
      gpu_count: 1
      memory: 24GB
    timeout: 4h
    description: "Train UNet++ with MobileNetV4 Hybrid backbone"

  # Execution 6: Quick Test
  - name: "Quick Test"
    script: training_unetpp.py
    args:
      - --backbone
      - resnet50
      - --deep_supervision
    environment:
      python_version: "3.10"
      requirements: requirements.txt
    resources:
      gpu: T4
      gpu_count: 1
      memory: 24GB
    timeout: 1h
    description: "Quick test run"

# Default settings for all executions
defaults:
  environment:
    python_version: "3.10"
    requirements: requirements.txt
  resources:
    region: auto  # Auto-select closest region
  sync:
    upload:
      - "*.py"
      - "src/**/*.py"
      - "config.py"
      - "requirements.txt"
    download:
      - "checkpoints_*/**"
      - "experiments/**"
      - "*.csv"
      - "*.png"
    exclude:
      - "__pycache__"
      - "*.pyc"
      - ".git"
      - "*.pth"  # Don't upload existing checkpoints
      - "datasets/**"  # Don't upload datasets

# Cost optimization
cost_control:
  max_cost_per_execution: 20.00  # USD
  auto_stop_on_completion: true
  idle_timeout: 5m  # Stop if idle for 5 minutes
